---
- name: "Install Local Consul Configuration and Restart"
  template: src=consul-client.conf.j2 dest=/etc/consul/consul-client.json
  notify:
  - restart consul

- name: "Install Consul's Nameservers on consul clients"
  # Note: change of resolv.conf doesn't require a restart
  # Note: ideally we should be editing /etc/resolvconf/resolv.conf.d/tail
  # but there're problems with that + AWS.
  template: src=resolv.conf-client.j2 dest=/etc/resolv.conf
              owner=root group=root mode="u=rw,g=r,o=r"